NAME = GMPUTILS
CC = gcc
CFLAGS = -Wall -lgmp

gmpUtils_getRandomPrime.o: gmpUtils_getRandomPrime.c
	$(CC) $(CFLAGS) -I../../include -o gmpUtils_getRandomPrime.o -c gmpUtils_getRandomPrime.c

gmpUtils_eulerTotient.o: gmpUtils_eulerTotient.c 
	$(CC) $(CFLAGS) -I../../include -o gmpUtils_eulerTotient.o -c gmpUtils_eulerTotient.c

gmpUtils_coprimeNumber.o: gmpUtils_coprimeNumber.c
	$(CC) $(CFLAGS) -I../../include -o gmpUtils_coprimeNumber.o -c gmpUtils_coprimeNumber.c

gmpUtils_gcd.o: gmpUtils_gcd.c
	$(CC) $(CFLAGS) -I../../include -o gmpUtils_gcd.o -c gmpUtils_gcd.c
